# Generated by Django 4.2.7 on 2023-11-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Assam', 'Assam'), ('Delhi', 'Delhi'), ('UK', 'UK'), ('UP', 'UP'), ('MP', 'MP'), ('HP', 'HP'), ('AP', 'AP'), ('MH', 'MH'), ('GJ', 'GJ')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('myfile', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
